development:
  adapter: postgresql
  encoding: unicode
  database: event_booker_development
  pool: 5
  username: ubuntu
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: event_booker_test
  pool: 5
  username: ubuntu
  password: password