development:
  adapter: postgresql
  encoding: unicode
  database: buy_tickets_development
  pool: 5
  username: ubuntu
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: buy_tickets_test
  pool: 5
  username: ubuntu
  password: password